@EmpCoreApiProject_HostAddress = http://localhost:5123

GET {{EmpCoreApiProject_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{EmpCoreApiProject_HostAddress}}/api/employee/

###

PUT {{EmpCoreApiProject_HostAddress}}/api/employee/{id:guid}
Content-Type: application/json

{
  //Guid
}

###

DELETE {{EmpCoreApiProject_HostAddress}}/api/employee/{id:guid}

###

GET {{EmpCoreApiProject_HostAddress}}/api/department/

###
